version: "3.8"

services:
  llama.cpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "8080:8080"
    volumes:
      - ${LLAMA_CPP_CACHE_DIR}:/root/.cache/llama.cpp
    command: >
      --hf-repo ${HF_LLM_REPO}
      --n-gpu-layers ${N_GPU_LAYERS}
      --no-kv-offload
      --ctx-size ${CTX_LENGTH}
      --n-predict ${LLM_MAX_TOKENS}
      --jinja
      --host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.18 # latest
    network_mode: "host"
    environment:
      - PORT=8081
      - OPENAI_API_BASE_URLS=http://pc-alice-ph01:8090/v1;http://pc-alice-ph01:8091/v1;http://pc-alice-ph01:8092/v1;http://pc-alice-ph01:8093/v1;http://pc-alice-ph01:8094/v1;${LLM_BASE_URL}
      - OPENAI_API_KEYS=any;any;any;any;any;${LLM_API_KEY}
      - WEBUI_AUTH=False
