version: "3.8"

services:
  llama.cpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "8080:8080"
    volumes:
      - ./models/llama.cpp:/root/.cache/llama.cpp
    command: >
      --hf-repo TheBloke/Mistral-7B-Instruct-v0.1-GGUF:Q4_K_M
      --host 0.0.0.0
      --n-gpu-layers 50
      --no-kv-offload
      --host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
