version: "3.8"

services:
  llama.cpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "8080:8080"
    volumes:
      - ${LLAMA_CPP_CACHE_DIR}:/root/.cache/llama.cpp
    command: >
      --hf-repo ${HF_LLM_REPO}
      --n-gpu-layers ${N_GPU_LAYERS}
      --no-kv-offload
      --host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
